env :
  name : 'duopoly_env'
  max_price : 2
  min_price : 0
  num_sellers : 2
  num_customers : 30
  memory_size : 5
  action_type : "disc"
  disc_action_size : 6
  max_steps : 500
  agent_ids : ["agent0", "agent1"]
  market : 
    demand_type : "Logit"
    logit : 
      a0 : 0
      cost : 1
      mu : 0.25
      a : 2
    linear :
training :
  algo : ["PPO", "PPO"]
  bs : 64
  iterations : 2
  exploration:
    type : 'EpsilonGreedy'
    initial_epsilon : 1.0
    final_epsilon : 0.02
    epsilon_timesteps : 10000